// examples/nextjs/BotCircuitsChat.jsx
import React, { useState, useRef, useEffect } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { BotCircuitsProvider, useBotCircuits } from 'botcircuits-client';

// Chat component that uses the BotCircuits hook
const ChatComponent = () => {
  const { messages, sendMessage, connectionStatus } = useBotCircuits();
  const [inputText, setInputText] = useState('');
  const messagesEndRef = useRef(null);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!inputText.trim()) return;

    try {
      await sendMessage({
        textMessage: inputText,
        requestAttributes: { phone_number: "94713132456" } // Example attribute
      });
      setInputText('');
    } catch (error) {
      console.error('Error sending message:', error);
    }
  };

  // Render different message types
  const renderMessage = (message) => {
    switch (message.type) {
      case 'TEXT':
        return <p>{message.content}</p>;
      
      case 'BUTTONS':
        return (
          <div className="buttons-message">
            <p>{message.content.displayText}</p>
            {message.content.optionsTitle && (
              <p className="options-title">{message.content.optionsTitle}</p>
            )}
            <div className="buttons-container">
              {message.content.buttons.map((button, index) => (
                <button
                  key={index}
                  className="button-option"
                  onClick={() => {
                    sendMessage({
                      textMessage: button.payload,
                      requestAttributes: { selected_button: button.payload }
                    });
                  }}
                >
                  {button.title}
                </button>
              ))}
            </div>
          </div>
        );
      
      case 'IMAGE':
        return (
          <div className="image-message">
            <img src={message.content.url} alt={message.content.caption || 'Bot image'} />
            {message.content.caption && <p>{message.content.caption}</p>}
          </div>
        );
      
      default:
        return <p>Unsupported message type: {message.type}</p>;
    }
  };

  return (
    <div className="chat-container">
      <div className="chat-header">
        <h2>BotCircuits Chat</h2>
        <div className={`connection-status status-${connectionStatus.toLowerCase()}`}>
          {connectionStatus}
        </div>
      </div>
      
      <div className="chat-messages">
        {messages.map((msg, index) => (
          <div key={index} className="message bot-message">
            {renderMessage(msg)}
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>
      
      <form className="chat-input-form" onSubmit={handleSubmit}>
        <input
          type="text"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Type a message..."
          disabled={connectionStatus !== 'CONNECTED'}
        />
        <button 
          type="submit" 
          disabled={!inputText.trim() || connectionStatus !== 'CONNECTED'}
        >
          Send
        </button>
      </form>
    </div>
  );
};

// BotCircuits Chat component with provider
const BotCircuitsChat = ({ appId, apiKey, host = 'pubsub.botcircuits.com' }) => {
  // Generate a unique session ID or use from props/cookies
  const sessionId = uuidv4();

  const options = {
    appId,
    apiKey,
    host
  };

  return (
    <BotCircuitsProvider options={options} sessionId={sessionId}>
      <ChatComponent />
    </BotCircuitsProvider>
  );
};

export default BotCircuitsChat;

// examples/angular/bot-circuits-chat.component.ts
import { Component, OnInit, OnDestroy, Input, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';
import { BotCircuitsService, Options, Message, Request, ConnectionStatus } from 'botcircuits-client';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-bot-circuits-chat',
  templateUrl: './bot-circuits-chat.component.html',
  styleUrls: ['./bot-circuits-chat.component.scss']
})
export class BotCircuitsChatComponent implements OnInit, OnDestroy, AfterViewChecked {
  @Input() appId!: string;
  @Input() apiKey!: string;
  @Input() host: string = 'pubsub.botcircuits.com';
  @Input() sessionId: string = uuidv4();
  
  @ViewChild('messagesContainer') private messagesContainer!: ElementRef;
  
  inputText: string = '';
  messages: Message[] = [];
  connectionStatus: ConnectionStatus = ConnectionStatus.DISCONNECTED;
  
  private messagesSubscription?: Subscription;
  private statusSubscription?: Subscription;
  private shouldScrollToBottom = false;
  
  constructor(private botCircuitsService: BotCircuitsService) {}
  
  ngOnInit(): void {
    // Initialize BotCircuits client
    const options: Options = {
      appId: this.appId,
      apiKey: this.apiKey,
      host: this.host
    };
    
    this.botCircuitsService.initialize(options, this.sessionId)
      .then(() => {
        console.log('BotCircuits client initialized');
      })
      .catch(error => {
        console.error('Failed to initialize BotCircuits client:', error);
      });
    
    // Subscribe to messages
    this.messagesSubscription = this.botCircuitsService.messages$.subscribe(messages => {
      this.messages = messages;
      this.shouldScrollToBottom = true;
    });
    
    // Subscribe to connection status
    this.statusSubscription = this.botCircuitsService.connectionStatus$.subscribe(status => {
      this.connectionStatus = status;
    });
  }
  
  ngAfterViewChecked(): void {
    if (this.shouldScrollToBottom) {
      this.scrollToBottom();
      this.shouldScrollToBottom = false;
    }
  }
  
  ngOnDestroy(): void {
    // Clean up subscriptions
    this.messagesSubscription?.unsubscribe();
    this.statusSubscription?.unsubscribe();
    
    // Clean up BotCircuits client
    this.botCircuitsService.cleanup();
  }
  
  /**
   * Send a message to the bot
   */
  sendMessage(): void {
    if (!this.inputText.trim()) return;
    
    const request: Request = {
      textMessage: this.inputText,
      requestAttributes: { phone_number: "94713132456" } // Example attribute
    };
    
    this.botCircuitsService.sendMessage(request)
      .then(() => {
        this.inputText = '';
      })
      .catch(error => {
        console.error('Error sending message:', error);
      });
  }
  
  /**
   * Handle button click
   */
  handleButtonClick(button: any): void {
    const request: Request = {
      textMessage: button.payload,
      requestAttributes: { selected_button: button.payload }
    };
    
    this.botCircuitsService.sendMessage(request)
      .catch(error => {
        console.error('Error sending button message:', error);
      });
  }
  
  /**
   * Clear all messages
   */
  clearMessages(): void {
    this.botCircuitsService.clearMessages();
  }
  
  /**
   * Scroll to the bottom of the messages container
   */
  private scrollToBottom(): void {
    try {
      this.messagesContainer.nativeElement.scrollTop = this.messagesContainer.nativeElement.scrollHeight;
    } catch (err) {
      console.error('Error scrolling to bottom:', err);
    }
  }
  
  /**
   * Check if the connection is active
   */
  isConnected(): boolean {
    return this.connectionStatus === ConnectionStatus.CONNECTED;
  }
}

<div class="chat-container">
  <div class="chat-header">
    <h2>BotCircuits Chat</h2>
    <div class="connection-status status-{{connectionStatus.toLowerCase()}}">
      {{connectionStatus}}
    </div>
  </div>
  
  <div class="chat-messages" #messagesContainer>
    <div *ngFor="let message of messages" class="message bot-message">
      <!-- Text message -->
      <div *ngIf="message.type === 'TEXT'">
        {{message.content}}
      </div>
      
      <!-- Buttons message -->
      <div *ngIf="message.type === 'BUTTONS'" class="buttons-message">
        <p>{{message.content.displayText}}</p>
        <p *ngIf="message.content.optionsTitle" class="options-title">
          {{message.content.optionsTitle}}
        </p>
        <div class="buttons-container">
          <button
            *ngFor="let button of message.content.buttons"
            class="button-option"
            (click)="handleButtonClick(button)"
          >
            {{button.title}}
          </button>
        </div>
      </div>
      
      <!-- Image message -->
      <div *ngIf="message.type === 'IMAGE'" class="image-message">
        <img [src]="message.content.url" [alt]="message.content.caption || 'Bot image'" />
        <p *ngIf="message.content.caption">{{message.content.caption}}</p>
      </div>
      
      <!-- Unsupported message type -->
      <div *ngIf="message.type !== 'TEXT' && message.type !== 'BUTTONS' && message.type !== 'IMAGE'">
        Unsupported message type: {{message.type}}
      </div>
    </div>
  </div>
  
  <form class="chat-input-form" (ngSubmit)="sendMessage()">
    <input
      [(ngModel)]="inputText"
      name="inputText"
      type="text"
      placeholder="Type a message..."
      [disabled]="!isConnected()"
    />
    <button 
      type="submit" 
      [disabled]="!inputText.trim() || !isConnected()"
    >
      Send
    </button>
  </form>
</div>
